---
concurrency:
  limit: 1
kind: pipeline
name: docs
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make doc
  image: thegeeklab/alpine-tools
  name: assets
- commands:
  - git-batch
  image: thegeeklab/git-batch
  name: sync
- commands:
  - markdownlint 'docs/content/**/*.md' 'README.md' 'CONTRIBUTING.md'
  image: thegeeklab/markdownlint-cli
  name: markdownlint
- commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'docs/content/**/*.md' 'README.md' -d .dictionary -p spell
    indefinite-article syntax-urls --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts-alpine
  name: spellcheck
- commands:
  - hugo -s docs/ -b http://localhost/
  image: thegeeklab/hugo:0.83.1
  name: testbuild
- commands:
  - link-validator -ro
  environment:
    LINK_VALIDATOR_BASE_DIR: docs/public
  image: thegeeklab/link-validator
  name: link-validation
- commands:
  - hugo -s docs/
  image: thegeeklab/hugo:0.83.1
  name: build
- commands:
  - npm install -g js-beautify
  - html-beautify -r -f 'docs/public/**/*.html'
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts-alpine
  name: beautify
- image: plugins/s3-sync
  name: publish
  settings:
    access_key:
      from_secret: s3_access_key
    bucket: geekdocs
    delete: true
    endpoint: https://sp.rknet.org
    path_style: true
    secret_key:
      from_secret: s3_secret_access_key
    source: docs/public/
    strip_prefix: docs/public/
    target: /${DRONE_REPO_NAME}
  when:
    ref:
    - refs/heads/main
    - refs/tags/**
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
---
kind: signature
hmac: ade2128e9bd2cdac2df077a5832d803252234bd4b9c50a1dcaaed1f94f1d1dee

...
